HashFans/HashkeyFans

src/components/redpacket/CreateRedPacket.tsx
=> fix: fix unit

src/app/[lang]/redpacket/[id]/page.tsx, src/app/[lang]/redpacket/create/page.tsx, src/components/redpacket/CreateRedPacket.tsx, src/config/contracts.ts, src/config/index.tsx
=> Feat redpocket

src/app/[lang]/redpacket/[id]/page.tsx, src/app/[lang]/redpacket/history/page.tsx, src/components/redpacket/RedPacketResult.tsx, src/components/redpacket/SuccessModal.tsx
=> fix: fix unit error

src/app/[lang]/redpacket/[id]/page.tsx, src/components/common/MobileMenu.tsx, src/components/common/NavLink.tsx
=> fix: mobile header problem

next.config.js
- add walletconnect for nextjs
=> fix: nextjs for walletconnect

src/app/[lang]/redpacket/[id]/page.tsx, src/hooks/useRedPacket.ts
=> chore: update unused variable

src/app/[lang]/redpacket/[id]/page.tsx, src/config/contracts.ts, src/config/index.tsx
- add share image
- add okx wallet support
=> feat: add share and okx wallet

package-lock.json, package.json, src/app/[lang]/layout.tsx, src/app/[lang]/redpacket/[id]/page.tsx, src/app/[lang]/redpacket/create/page.tsx, src/app/[lang]/redpacket/history/page.tsx, src/components/redpacket/CreateRedPacket.tsx, src/components/redpacket/ShareModal.tsx, src/components/redpacket/SuccessModal.tsx, src/i18n/locales/en.ts, src/i18n/locales/zh.ts, yarn.lock
feat: add multi language support
=> feat: add multi language support

src/app/[lang]/redpacket/[id]/page.tsx, src/i18n/locales/en.ts, src/i18n/locales/zh.ts
=> feat: add best lucy

src/data/projectsData.ts
=> fix: fix url of asteroidx.io

src/components/redpacket/SuccessModal.tsx
=> fix: remove unused comment

src/app/[lang]/client-provider.tsx, src/app/[lang]/projects/page.tsx, src/app/[lang]/redpacket/[id]/page.tsx, src/app/[lang]/redpacket/create/page.tsx, src/app/[lang]/redpacket/history/page.tsx, src/config/contracts.ts, src/hooks/useRedPacket.ts, src/i18n/locales/en.ts, src/i18n/locales/zh.ts
- feat: add feature of reclaim red packet more than 24h
=> feat: add feature of reclaim red packet more than 24h

src/app/[lang]/client-provider.tsx, src/app/[lang]/redpacket/[id]/page.tsx
=> fix: fix unused variable

src/components/layout/Header.tsx
=> fix: add text color to header

src/components/layout/Header.tsx
=> fix: typo fix

src/components/layout/Header.tsx
=> fix: fix header problem

src/components/layout/Header.tsx
- remove finished activity 圆币
- change redpacket back
=> fix: update typo header

src/app/[lang]/redpacket/page.tsx, src/app/globals.css, src/components/layout/Header.tsx, src/config/menu.ts, src/i18n/locales/en.ts, src/i18n/locales/zh.ts, src/types/menu.ts
=> fix: change header

src/components/layout/Header.tsx, src/lib/utils.ts
=> fix: remove unused params

src/app/[lang]/profile/page.tsx, src/app/api/user/collection-status/route.ts
=> fix: card error

public/content/news/en/taichu-hackerhouse-launch.mdx, public/content/news/zh/taichu-hackerhouse-launch.mdx, src/app/[lang]/layout.tsx, src/components/common/SocialLinks.tsx, src/components/layout/Footer.tsx
=> update: update twitter handle

next.config.mjs
update: remove eslint build check
=> update: remove eslint build check

src/components/layout/Header.tsx
- change header color for light system
=> fix: fix theme color
